# docker-composeのバージョン
version: '3'
services:
  # サービス名（docker-compose app のような形式でこのコンテナに対して命令が出来る）
  app:
    # buildで利用するオプションを指定する
    build:
      # どこをカレントディレクトリとしてdockerfileのパスを示すか指定する
      context: .
      # buildで利用するDockerfileのパスを指定する
      dockerfile: ./Dockerfile
    # ttyコマンドで仮想端末を置いて、コンテナのフォアグラウンドプロセスを実行する
    # https://zenn.dev/hohner/articles/43a0da20181d34
    tty: true
    # 標準入出力とエラー出力をコンテナに結びつける（デバッグ用）
    # https://qiita.com/yuki_0920/items/dc3f32667d004979cc5a#stdin_open-true%E3%81%A8%E3%81%AF%E4%BD%95%E3%81%8B
    stdin_open: true
    # カレントディレクトリをWORKDIRにマウントする
    # ※ volumesは配列である必要があるので、'-'を付けることでYAMLの配列とする
    # https://magazine.rubyist.net/articles/0009/0009-YAML.html
    volumes:
      - .:/go_dev_container